version: 2
before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/batcha
    binary: batcha
    ldflags:
      - -s -w -X github.com/kyosu-1/batcha.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format_overrides:
      - goos: windows
        formats: [zip]
brews:
  - repository:
      owner: kyosu-1
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/kyosu-1/batcha
    description: Declarative deployment tool for AWS Batch Job Definitions
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
